### ISSUE TITLE
[질문] GitGuardian 보안 경고가 떴습니다.

### ISSUE THREAD

**Issue by Dragon0111ga** [Dragon0111ga/BaekJiJang#11]
GitGuardian이 GitHub 계정에 노출 된 Google의 API 키를 감지했다고
연동하라는데 연동해도 교수님이 평가하시는 데에는 문제가 없는건가요?

**Comment by yuhanappdev** [comment]
이번주 강의에 얘기한 내용인데 google의 API KEY를 깃헙에 올리면 다른 사람들이 해당 키값을 보고 무단 사용할 수 있으니 소스에서 API 키 저장하는 부분을 공백으로 바꾸고 commit 및 push하면 되요.
